// wiki-content.json is generated by build_site.py before Netlify bundles
// the function; esbuild inlines it at bundle time via require().
let wikiPages = [];
try {
  wikiPages = require("./wiki-content.json");
} catch {
  // not present in local dev without running build_site.py first
}

function score(page, words) {
  const hay = `${page.title} ${page.content}`.toLowerCase();
  return words.filter((w) => hay.includes(w)).length;
}

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
};

exports.handler = async function (event) {
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 204, headers: CORS, body: "" };
  }
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, headers: CORS, body: "Method Not Allowed" };
  }

  let question;
  try {
    ({ question } = JSON.parse(event.body));
  } catch {
    return {
      statusCode: 400,
      headers: CORS,
      body: JSON.stringify({ error: "Invalid JSON body" }),
    };
  }

  if (!question || typeof question !== "string" || !question.trim()) {
    return {
      statusCode: 400,
      headers: CORS,
      body: JSON.stringify({ error: "question is required" }),
    };
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return {
      statusCode: 500,
      headers: CORS,
      body: JSON.stringify({ error: "OPENAI_API_KEY not configured on server" }),
    };
  }

  const words = question.toLowerCase().split(/\s+/).filter((w) => w.length > 2);
  const sorted = [...wikiPages]
    .map((p) => ({ ...p, _score: score(p, words) }))
    .sort((a, b) => b._score - a._score);

  const relevant = sorted.filter((p) => p._score > 0).slice(0, 8);
  const pool = relevant.length ? relevant : sorted.slice(0, 6);

  const context = pool
    .map((p) => `## ${p.title}\n${p.content.slice(0, 3000)}`)
    .join("\n\n---\n\n");

  const oaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            "You are a friendly assistant for a private Israeli friend-group wiki. " +
            "Answer questions using only the wiki pages below. Be specific and conversational. " +
            "If something isn't in the wiki, say so honestly.\n\nWiki:\n\n" +
            context,
        },
        { role: "user", content: question },
      ],
      max_tokens: 800,
    }),
  });

  if (!oaiRes.ok) {
    const detail = await oaiRes.text();
    return {
      statusCode: 502,
      headers: CORS,
      body: JSON.stringify({ error: "OpenAI error", detail }),
    };
  }

  const data = await oaiRes.json();
  const answer = data.choices?.[0]?.message?.content ?? "No answer received.";
  const sources = pool.map((p) => ({ title: p.title, url: p.url }));

  return {
    statusCode: 200,
    headers: { ...CORS, "Content-Type": "application/json" },
    body: JSON.stringify({ answer, sources }),
  };
};
